# Generated by Django 3.2.3 on 2021-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('writer', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('writerImg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ingredientBit', models.IntegerField(default=0)),
                ('ingredientDetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writerID', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('contents', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=32)),
                ('postImg', models.ImageField(upload_to='')),
                ('userImg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('filterBit', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=64)),
                ('userImg', models.ImageField(upload_to='')),
            ],
        ),
    ]
